//! Generates `Shared/generated-ts` from the Rust contracts (invariant 22).
//!
//! This binary is what makes "Rust is the source of truth" operative rather
//! than aspirational. ADR-003 records hand-mirrored TypeScript and Rust types
//! as a known source of drift; the fix is that one side is generated and the
//! generated side is never edited (invariant 23).

#![forbid(unsafe_code)]

use std::path::PathBuf;

use gx_asset_plane::{AssetRef, PreflightRequest, PreflightResponse, TransferState};
use gx_contracts::{
    ClockSource, ContentHash, DeviceTier, Locality, MediaCodec, RationalRate, ReferenceState,
    Refusal, Revision, TakeId,
};
use gx_control_plane::{EngineCapability, TakeAt, TakeCommitted, TakeRequest};
use gx_media_plane::{ConsumerRole, DropCounters, MediaProfile};
use ts_rs::TS;

/// Every root type that crosses a plane boundary. Adding a contract type
/// without adding it here means TypeScript never sees it, so this list is the
/// one place to look when a type is missing downstream.
macro_rules! export_all {
    ($dir:expr, $($ty:ty),+ $(,)?) => {{
        let mut count = 0usize;
        $(
            <$ty as TS>::export_all_to($dir)?;
            count += 1;
        )+
        count
    }};
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let out = workspace_root().join("Shared/generated-ts/src");
    std::fs::create_dir_all(&out)?;

    let count = export_all!(
        &out,
        // gx-contracts
        TakeId,
        ContentHash,
        Revision,
        RationalRate,
        Locality,
        DeviceTier,
        ClockSource,
        ReferenceState,
        Refusal,
        // gx-control-plane
        TakeAt,
        TakeRequest,
        TakeCommitted,
        EngineCapability,
        MediaCodec,
        // gx-asset-plane
        AssetRef,
        PreflightRequest,
        PreflightResponse,
        TransferState,
        // gx-media-plane
        ConsumerRole,
        MediaProfile,
        DropCounters,
    );

    write_barrel(&out)?;
    println!("generated {count} contract types into {}", out.display());
    Ok(())
}

/// Writes `index.ts` re-exporting every generated declaration, so consumers
/// import from one place and a renamed type breaks the build loudly.
fn write_barrel(dir: &std::path::Path) -> std::io::Result<()> {
    let mut names: Vec<String> = std::fs::read_dir(dir)?
        .filter_map(|e| e.ok())
        .filter_map(|e| {
            let name = e.file_name().to_string_lossy().into_owned();
            let stem = name.strip_suffix(".ts")?.to_string();
            (stem != "index").then_some(stem)
        })
        .collect();
    names.sort();

    let mut body = String::from(
        "// GENERATED by gx-contract-codegen. Do not edit (invariant 23).\n\
         // Regenerate with `npm run codegen`.\n\n",
    );
    for name in &names {
        body.push_str(&format!("export * from \"./{name}\";\n"));
    }
    std::fs::write(dir.join("index.ts"), body)
}

/// The workspace root, derived from this crate's manifest directory rather
/// than from the current working directory, so the output lands in the same
/// place however the binary is invoked.
fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("crate lives two levels below the workspace root")
        .to_path_buf()
}
