// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How alpha is interpreted. Straight and premultiplied are different images,
 * and guessing between them is a visible halo on every soft edge.
 */
export type AlphaMode = "opaque" | "straight" | "premultiplied" | "alpha-test";
