// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether an asset's bytes are available where they are needed.
 */
export type AssetAvailability = "Ready" | "Missing" | "Importing" | "Unsupported" | "Error";
