// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentHash } from "./ContentHash";

/**
 * How an asset is addressed. Both modes are retained deliberately
 * (invariant 31): the hash addresses the store, the path addresses the
 * library, so replacing a file in place keeps material bindings intact.
 */
export type AssetRef = { "kind": "content", hash: ContentHash, } | { "kind": "path", path: string, };
