// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetAvailability } from "./AssetAvailability";
import type { AssetKind } from "./AssetKind";
import type { ContentHash } from "./ContentHash";

/**
 * An asset as the library knows it. Carries **both** addresses: the content
 * hash (immutable, addresses the store) and the project-relative path
 * (mutable, addresses the library). The hash is what a scene's bindings
 * resolve against, so re-importing over the same path — a new render of the
 * same logo — updates the hash but never the binding.
 */
export type AssetLibraryItem = { 
/**
 * Stable scene-facing id. Survives relink; distinct from any storage id.
 */
assetId: string, 
/**
 * Display name, separate from the on-disk name (ADR-0002 B.3).
 */
name: string, kind: AssetKind, 
/**
 * Project-relative path — the library address.
 */
path: string, 
/**
 * Content hash — the store address. `None` only while importing.
 */
checksum?: ContentHash, mimeType?: string, sizeBytes?: bigint, status?: AssetAvailability, };
