// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Vec2 } from "./Vec2";

/**
 * A cubic bezier path, structured like Lottie/Bodymovin's "sh" shape so it
 * round-trips with the web's proven vector-animation format. Segment k→k+1 is
 * a cubic bezier; tangents are relative to their vertex. All three arrays
 * must be the same length — the constraint that also makes a path animatable.
 */
export type BezierPath = { closed: boolean, vertices: Array<Vec2>, inTangents: Array<Vec2>, outTangents: Array<Vec2>, };
