// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Every blend mode the authoring vocabulary contains, supported or not.
 *
 * Carried across from 1.x `MATERIAL_BLEND_MODES` unchanged, because a scene
 * authored there must mean the same thing here.
 */
export type BlendMode = "normal" | "add" | "multiply" | "screen" | "overlay" | "darken" | "lighten" | "subtract" | "alpha-mask" | "inverse-alpha-mask";
