// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A brush point: position, pressure, time.
 */
export type BrushPoint = { x: number, y: number, pressure?: number, time?: number, };
