// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TakeAt } from "./TakeAt";

/**
 * Clear Program. Also intent-based: the operator asks, the engine says when.
 */
export type ClearRequest = { at: TakeAt, };
