// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClearRequest } from "./ClearRequest";
import type { CueRequest } from "./CueRequest";
import type { OutputConfig } from "./OutputConfig";
import type { TakeRequest } from "./TakeRequest";

/**
 * Everything a client may ask for. Playout may send all of these; the Editor
 * may send none of the Program-affecting ones (invariants 4 and 5), which is
 * enforced by the command surfaces each product exposes rather than by a flag
 * on the message.
 */
export type ClientRequest = { "request": "authenticate", token: string, } | { "request": "capability" } | { "request": "status" } | { "request": "cue" } & CueRequest | { "request": "take" } & TakeRequest | { "request": "clear" } & ClearRequest | { "request": "configureOutput" } & OutputConfig;
