// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the render node's phase comes from. Reported, never requested.
 */
export type ClockSource = "Genlocked" | "Ptp" | "FreeRun";
