// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RationalRate } from "./RationalRate";
import type { Severity } from "./Severity";

/**
 * The operator-facing summary of clock state.
 *
 * Returned as a struct with a severity rather than a formatted string, so the
 * UI cannot accidentally present a `Critical` state with `Nominal` styling.
 */
export type ClockSummary = { severity: Severity, 
/**
 * Short, unambiguous label. Never abbreviated to something an operator
 * has to decode mid-show.
 */
label: string, timebase: RationalRate, 
/**
 * True when Program cadence is not derived from an external reference.
 */
freeRunning: boolean, };
