// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GradientCoordinateMode } from "./GradientCoordinateMode";
import type { GradientSpread } from "./GradientSpread";
import type { GradientStop } from "./GradientStop";
import type { Rgba } from "./Rgba";

/**
 * An authored paint: nothing, a colour, or a gradient.
 *
 * `None` is a value, not an absence — "the author turned the fill off" and
 * "the author has not set a fill" are different states, and collapsing them
 * is how a transparent object becomes a black one on the other renderer.
 * Ported from 1.x `ColorValue`, with every colour now tagged.
 */
export type ColorValue = { "type": "none" } | { "type": "solid", color: Rgba, } | { "type": "linear-gradient", 
/**
 * Degrees, clockwise from the positive X axis.
 */
angle: number, startX: number, startY: number, endX: number, endY: number, stops: Array<GradientStop>, spread: GradientSpread, coordinateMode: GradientCoordinateMode, } | { "type": "radial-gradient", centerX: number, centerY: number, radiusX: number, radiusY: number, focalX?: number, focalY?: number, stops: Array<GradientStop>, spread: GradientSpread, coordinateMode: GradientCoordinateMode, };
