// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the consumer needs, which is not the same as what it is.
 *
 * A designer dragging a handle and an operator watching a confidence monitor
 * have different requirements from the same pixels (ADR-004).
 */
export type ConsumerRole = "Interactive" | "Observational";
