// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Content address of asset bytes: SHA-256, lowercase hex.
 */
export type ContentHash = string;
