// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Revision } from "./Revision";
import type { TakeAt } from "./TakeAt";
import type { TakeId } from "./TakeId";

/**
 * Ask for a cue: prepare a scene without putting it to air.
 *
 * Cue carries intent for the same reason take does. A cue that is resolved
 * against the client's clock would prepare against the wrong frame and the
 * error would only show up as a late first frame on air.
 */
export type CueRequest = { takeId: TakeId, revision: Revision, at: TakeAt, };
