// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which faces are drawn. Carried from 1.x `MaterialCullMode`.
 */
export type CullMode = "none" | "front" | "back";
