// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceTier } from "./DeviceTier";
import type { RationalRate } from "./RationalRate";

/**
 * Why the engine is not in a fully healthy state.
 *
 * Enumerated rather than a free-text message: an operator display has to be
 * able to decide severity, and a string cannot be matched on.
 */
export type Degradation = { "degradation": "referenceLost", was: RationalRate, } | { "degradation": "freeRunning" } | { "degradation": "deviceBelowT0", actual: DeviceTier, };
