// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Render device capability tier. Only T0 may go to air (invariant 19).
 */
export type DeviceTier = "T0" | "T1" | "T2" | "T3";
