// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Frames discarded because the consumer could not keep up, counted by cause.
 *
 * Counted rather than buffered: a queue here would eventually push back on
 * the render clock, which invariant 14 forbids.
 */
export type DropCounters = { 
/**
 * Consumer was still handling the previous frame.
 */
consumerBusy: bigint, 
/**
 * Encoder had no capacity.
 */
encoderSaturated: bigint, 
/**
 * Transport backpressure.
 */
transportFull: bigint, };
