// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenRef } from "./TokenRef";

/**
 * A duration: a token reference or a literal millisecond count.
 */
export type DurationSpec = TokenRef | number;
