// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a font's bytes may travel inside a `.gpxpkg` — the licensing
 * decision made per font (docs/p2-licensing-positions.md §5).
 */
export type EmbeddingPolicy = "package" | "reference" | "restricted";
