// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineCapability } from "./EngineCapability";
import type { EngineStatus } from "./EngineStatus";
import type { Refusal } from "./Refusal";
import type { TakeCommitted } from "./TakeCommitted";

/**
 * Everything the engine may answer. A refusal is a reply, not an exception:
 * it travels the same path and is as much a defined outcome as success.
 */
export type EngineReply = { "reply": "authenticated" } | { "reply": "capability" } & EngineCapability | { "reply": "status" } & EngineStatus | { "reply": "cued" } & TakeCommitted | { "reply": "taken" } & TakeCommitted | { "reply": "cleared" } & TakeCommitted | { "reply": "outputConfigured", adapter: string, live: boolean, } | { "reply": "refused" } & Refusal;
