// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClockSource } from "./ClockSource";
import type { DeviceTier } from "./DeviceTier";
import type { Epoch } from "./Epoch";
import type { Locality } from "./Locality";
import type { MediaCodec } from "./MediaCodec";
import type { ReferenceState } from "./ReferenceState";

/**
 * What the engine tells a connecting client about itself.
 */
export type EngineCapability = { 
/**
 * Fixed constant. A mismatch is an error code, not a negotiation.
 */
protocol: number, 
/**
 * Engine incarnation. A client that reconnects and sees a new epoch must
 * assume none of its previous state survived.
 */
epoch: Epoch, locality: Locality, deviceTier: DeviceTier, clock: ClockSource, reference: ReferenceState, 
/**
 * Derived from ADR-005. Never set by hand, never inferred from an adapter
 * name (invariant 20).
 */
liveAllowed: boolean, 
/**
 * Offered, in preference order.
 */
media: Array<MediaCodec>, };
