// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClockSource } from "./ClockSource";
import type { Degradation } from "./Degradation";
import type { DeviceTier } from "./DeviceTier";
import type { Epoch } from "./Epoch";
import type { ProgramState } from "./ProgramState";
import type { RationalRate } from "./RationalRate";
import type { ReferenceState } from "./ReferenceState";

/**
 * The engine's reported state. The single source for every operator display.
 */
export type EngineStatus = { epoch: Epoch, currentFrame: bigint, timebase: RationalRate, clock: ClockSource, reference: ReferenceState, deviceTier: DeviceTier, 
/**
 * Derived from ADR-005 conditions. Never inferred from an adapter name
 * (invariant 20).
 */
liveAllowed: boolean, program: ProgramState | null, 
/**
 * Empty means healthy. Order is not significant.
 */
degradations: Array<Degradation>, };
