// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClockSource } from "./ClockSource";
import type { DeviceTier } from "./DeviceTier";
import type { Locality } from "./Locality";
import type { MediaCodec } from "./MediaCodec";
import type { ReferenceState } from "./ReferenceState";

/**
 * Capability exchange, extended for locality and clock (ADR-002 action 2).
 */
export type EngineCapability = { 
/**
 * Fixed constant. A mismatch is an error code, not a negotiation.
 */
protocol: number, locality: Locality, deviceTier: DeviceTier, clock: ClockSource, reference: ReferenceState, 
/**
 * Derived from ADR-005. Never set by hand, never inferred from an adapter
 * name (invariant 20).
 */
liveAllowed: boolean, 
/**
 * Offered, in preference order.
 */
media: Array<MediaCodec>, };
