// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceTier } from "./DeviceTier";
import type { ReferenceTransition } from "./ReferenceTransition";
import type { TakeCommitted } from "./TakeCommitted";

/**
 * Unsolicited engine events. Never share an id with a reply (invariant 33).
 */
export type EngineEvent = { "event": "referenceChanged" } & ReferenceTransition | { "event": "deviceTierChanged", from: DeviceTier, to: DeviceTier, } | { "event": "committed" } & TakeCommitted;
