// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClockSource } from "./ClockSource";
import type { DeviceTier } from "./DeviceTier";
import type { Epoch } from "./Epoch";
import type { Locality } from "./Locality";
import type { MaterialSupport } from "./MaterialSupport";
import type { MediaCodec } from "./MediaCodec";
import type { ReferenceState } from "./ReferenceState";

/**
 * What the engine tells a connecting client about itself.
 */
export type EngineCapability = { 
/**
 * Fixed constant. A mismatch is an error code, not a negotiation.
 */
protocol: number, 
/**
 * Engine incarnation. A client that reconnects and sees a new epoch must
 * assume none of its previous state survived.
 */
epoch: Epoch, locality: Locality, deviceTier: DeviceTier, clock: ClockSource, reference: ReferenceState, 
/**
 * Derived from ADR-005. Never set by hand, never inferred from an adapter
 * name (invariant 20).
 */
liveAllowed: boolean, 
/**
 * Offered, in preference order.
 */
media: Array<MediaCodec>, 
/**
 * The blend and fit modes this engine can reproduce exactly (1.3).
 *
 * Declared, like locality and tier, and for the same reason: what a
 * device can actually draw is a measured property of that device, not
 * something a client may infer from a version or a build flag
 * (invariant 21). A validator refuses a material against *this* list,
 * so an engine that has no rasteriser yet declares none and every mode
 * refuses by name — which is the correct answer, not a degraded one.
 */
material: MaterialSupport, };
