// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Engine incarnation counter. Bumped on every engine start.
 *
 * Reconnect reconciles by revision *and* epoch (ADR B.4): a matching revision
 * from a previous epoch means the engine restarted, and a client that ignores
 * the epoch would assume state it no longer has.
 */
export type Epoch = bigint;
