// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How texture content is mapped into the box it is drawn in.
 *
 * One vocabulary, merged from 1.x's two: `contain` is the mode its texture
 * enum called `fit`, and `cover` is the one it called `fill`. The names kept
 * are CSS's, because that is the vocabulary designers hand work over in.
 */
export type FitMode = "stretch" | "contain" | "cover" | "crop" | "tile" | "original" | "pixel-perfect" | "nine-slice";
