// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FontLoadStatus } from "./FontLoadStatus";
import type { FontSource } from "./FontSource";
import type { FontStyle } from "./FontStyle";

/**
 * One face of a family: weight/style/stretch with a source.
 */
export type FontFaceDefinition = { faceId: string, family: string, 
/**
 * CSS weight scale, 1–1000.
 */
weight: number, style: FontStyle, stretch?: string, unicodeRange?: string, source: FontSource, status?: FontLoadStatus, errorMessage?: string, };
