// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EmbeddingPolicy } from "./EmbeddingPolicy";
import type { FontFaceDefinition } from "./FontFaceDefinition";
import type { FontLoadStatus } from "./FontLoadStatus";

/**
 * A family as the scene knows it: its faces, fallbacks and licensing
 * posture. Embedded verbatim in the scene document, so a package is
 * self-describing.
 */
export type FontDefinition = { fontId: string, family: string, displayName: string, faces: Array<FontFaceDefinition>, fallbackFamilies: Array<string>, embeddingPolicy: EmbeddingPolicy, 
/**
 * The declared licence. A `Package` font without one is a preflight
 * refusal (p2-licensing-positions §5: unstated licence ⇒ restricted).
 */
license?: string, enabled: boolean, sourceLabel?: string, status: FontLoadStatus, errorMessage?: string, };
