// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Font container formats the pipeline accepts. WOFF/WOFF2 are delivery
 * wrappers; the shaper sees the same tables either way.
 */
export type FontFormat = "otf" | "ttf" | "woff" | "woff2";
