// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FontFormat } from "./FontFormat";

/**
 * Where a face's bytes come from.
 *
 * `rename_all_fields` (not `rename_all`) because the variant *fields* are
 * what hit the wire: `rename_all` alone would leave `asset_id` snake_case
 * while every other contract is camelCase.
 */
export type FontSource = { "kind": "file", assetId: string, format: FontFormat, 
/**
 * Original public URL when this face was resolved and cached from CSS.
 */
originalUrl?: string, 
/**
 * Stylesheet that declared this cached face.
 */
stylesheetUrl?: string, } | { "kind": "cssUrl", url: string, integrity?: string, } | { "kind": "adobeFonts", projectId: string, url: string, } | { "kind": "directUrl", url: string, format?: FontFormat, };
