// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Load state of a font or face. `Missing` at preflight is a refusal
 * (`Refusal::FontMissing`), never a fallback to a system font.
 */
export type FontLoadStatus = "Loading" | "Ready" | "Missing" | "Invalid" | "Unsupported" | "Unverified" | "Error";
