// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a gradient's coordinates are the object's or the scene's. An
 * object-space gradient follows its object; a scene-space one stays put
 * while the object moves through it.
 */
export type GradientCoordinateMode = "object" | "scene";
