// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a gradient does outside its 0–1 span. CSS's own names.
 */
export type GradientSpread = "pad" | "repeat" | "reflect";
