// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A group: a hierarchy container that affects descendants but paints no
 * pixels. Children are object ids, in scene order.
 */
export type GroupObject = { childIds: Array<string>, id: string, name: string, visible: boolean, 
/**
 * 0–1.
 */
opacity: number, 
/**
 * Translation in scene coordinates.
 */
x: number, y: number, scaleX: number, scaleY: number, 
/**
 * Rotation in degrees.
 */
rotation: number, };
