// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HierarchyChildren } from "./HierarchyChildren";
import type { HierarchyDiagnostic } from "./HierarchyDiagnostic";
import type { HierarchyEdge } from "./HierarchyEdge";
import type { ResolvedObject } from "./ResolvedObject";

/**
 * The result of resolving a scene's hierarchy.
 */
export type HierarchyResolution = { 
/**
 * Every object's effective state, in the document's source order.
 * Containers are included and marked, because the editor needs a group's
 * effective placement even though nothing draws it.
 */
effective: Array<ResolvedObject>, 
/**
 * The accepted edges, in the order they were taken.
 */
edges: Array<HierarchyEdge>, 
/**
 * Each container's accepted, validated child order, in source order.
 */
childrenByParent: Array<HierarchyChildren>, 
/**
 * Every refused edge, in the order encountered. A refusal is reported and
 * never fatal: a scene being repaired in the editor still resolves.
 */
diagnostics: Array<HierarchyDiagnostic>, };
