// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An accepted parent → child edge.
 */
export type HierarchyEdge = { parentId: string, childId: string, };
