// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why an edge was not taken.
 */
export type HierarchyDiagnosticCode = "missing-child" | "self-reference" | "multiple-parents" | "cycle";
