// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A container's accepted children, in the order it claimed them.
 */
export type HierarchyChildren = { parentId: string, childIds: Array<string>, };
