// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An image. The asset is referenced by id into the scene's asset library —
 * the stable address, so a replace-in-place keeps this binding (1.7).
 */
export type ImageObject = { 
/**
 * References `AssetLibraryItem::asset_id` in the scene's `assets`.
 */
assetId: string, width?: number, height?: number, id: string, name: string, visible: boolean, 
/**
 * 0–1.
 */
opacity: number, 
/**
 * Translation in scene coordinates.
 */
x: number, y: number, scaleX: number, scaleY: number, 
/**
 * Rotation in degrees.
 */
rotation: number, };
