// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";
import type { LightKind } from "./LightKind";
import type { Vec2 } from "./Vec2";
import type { Vec3 } from "./Vec3";

/**
 * A light source. Affects meshes; paints no pixels itself.
 */
export type LightObject = { lightKind: LightKind, intensity: number, color: string, 
/**
 * Distance at which a point or spot light's intensity reaches zero.
 * Absent means no cut-off.
 */
range?: number, 
/**
 * Falloff exponent over `range`.
 */
decay?: number, 
/**
 * Spot cone half-angle in degrees, and the 0–1 softness of its edge.
 */
coneAngleDeg?: number, penumbra?: number, 
/**
 * Point the light aims at, for directional and spot lights.
 */
target?: Vec3, castShadow: boolean, id: string, name: string, visible: boolean, locked: boolean, 
/**
 * 0–1.
 */
opacity: number, 
/**
 * Translation in scene coordinates (top-left authoring origin).
 */
x: number, y: number, 
/**
 * Depth along the view axis; composes additively down the hierarchy.
 */
zDepth: number, 
/**
 * Draw order within a layer.
 */
zIndex: number, 
/**
 * The layer this object belongs to (a `Layer` object's id), or empty for
 * the implicit default layer.
 */
layerId: string, 
/**
 * The object's box, in scene units. Every kind has one: a rect and an
 * image fill it, an ellipse is inscribed in it, paragraph text wraps
 * inside it, and a binding can drive it — which is why it is on the base
 * and not repeated per kind.
 */
width: number, height: number, 
/**
 * Rotation in degrees. `rotation` is the Z axis; X and Y are 3D and
 * compose down the hierarchy only on meshes (`resolve_hierarchy`).
 */
rotation: number, rotationX: number, rotationY: number, scaleX: number, scaleY: number, scaleZ: number, 
/**
 * Object-local pivot in scene pixels; renderers apply T(x,y)·R·S·T(-anchor).
 */
anchor?: Vec2, 
/**
 * Primary fill and stroke, as a CSS colour string. The rich colour model
 * (gradients, tagged source spaces) is 1.4's.
 */
fill?: string, stroke?: string, strokeWidth: number, 
/**
 * Bound data paths (object property → data-context path). Opaque here;
 * the binding contract owns the grammar.
 */
bindings?: { [key in string]?: JsonValue }, 
/**
 * Material slot assignments (slot name → material id). Opaque until
 * 1.3's material model types the value.
 */
materialSlots?: { [key in string]?: JsonValue }, };
