// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the engine is relative to its clients. Declared in the capability
 * exchange; selects transport and media encoding (ADR-001, ADR-004).
 */
export type Locality = "CoLocated" | "Lan";
