// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlphaMode } from "./AlphaMode";
import type { BlendMode } from "./BlendMode";
import type { ColorValue } from "./ColorValue";
import type { CullMode } from "./CullMode";
import type { DepthMode } from "./DepthMode";
import type { MaterialKind } from "./MaterialKind";
import type { MaterialTextureSlot } from "./MaterialTextureSlot";

/**
 * A material as the library holds it.
 */
export type MaterialDefinition = { materialId: string, name: string, kind: MaterialKind, 
/**
 * The base paint. A gradient is a colour value rather than a separate
 * material kind, so a fill can become a gradient without the material
 * changing type underneath every object that uses it.
 */
color: ColorValue, 
/**
 * 0–1, multiplied with the object's own opacity.
 */
opacity: number, blendMode: BlendMode, alphaMode: AlphaMode, cullMode: CullMode, depthMode: DepthMode, doubleSided: boolean, textures: Array<MaterialTextureSlot>, 
/**
 * Set only for `MaterialKind::Shader`.
 */
shaderId?: string, };
