// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an object's material slot points at.
 *
 * 1.x allowed either a bare material id string *or* an object with
 * overrides in the same field. An untagged union like that deserialises by
 * trial, and a shape that nearly matches the wrong arm is accepted silently,
 * so only the object form is carried.
 */
export type MaterialBinding = { materialId: string, 
/**
 * An instance of the material carrying its own parameter overrides.
 */
instanceId?: string, };
