// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a material fundamentally is.
 *
 * 1.x carried fifteen values here, ten of which its loader rewrote to `pbr`
 * on the way in — load-only compatibility aliases for a format 2.0 does not
 * read. Only the kinds that behave differently are carried.
 */
export type MaterialKind = "solid-color" | "image" | "video" | "pbr" | "unlit" | "shader";
