// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlendMode } from "./BlendMode";
import type { FitMode } from "./FitMode";

/**
 * The blend and fit modes a peer declares it can actually draw.
 *
 * Held as data and exchanged in the capability handshake, never derived from
 * a feature flag (invariant 21): "this build has shader compositing compiled
 * in" is not the same claim as "this device draws overlay correctly".
 */
export type MaterialSupport = { blendModes: Array<BlendMode>, fitModes: Array<FitMode>, };
