// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Codecs the media plane may negotiate.
 *
 * Lives here rather than in either plane: the control plane offers the set in
 * its capability exchange and the media plane negotiates from it, so putting
 * it in one of them would couple two planes that ADR-001 keeps independent.
 */
export type MediaCodec = "RawShared" | "Jpeg" | "H264" | "Hevc";
