// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaCodec } from "./MediaCodec";

/**
 * The negotiated shape of one media stream.
 */
export type MediaProfile = { codec: MediaCodec, 
/**
 * Whether the stream may reduce resolution to hold latency.
 */
adaptiveResolution: boolean, };
