// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorValue } from "./ColorValue";
import type { JsonValue } from "./serde_json/JsonValue";
import type { MaterialBinding } from "./MaterialBinding";
import type { MeshPrimitiveKind } from "./MeshPrimitiveKind";
import type { SlabProperties } from "./SlabProperties";
import type { Vec2 } from "./Vec2";
import type { Vec3 } from "./Vec3";

/**
 * A 3D mesh: a primitive or an imported glTF model. Meshes are the only
 * objects whose X/Y rotations compose down the hierarchy.
 */
export type MeshObject = { meshKind: MeshPrimitiveKind, 
/**
 * Extrusion depth in scene units.
 */
depth: number, 
/**
 * Slab controls. Present only for `MeshPrimitiveKind::Slab`.
 */
slab?: SlabProperties, 
/**
 * References an `AssetLibraryItem` of kind `Model`. Required by
 * `MeshPrimitiveKind::Model` and meaningless for the primitives.
 */
modelAssetId?: string, 
/**
 * Ordered material element names read from the imported model's
 * metadata, so per-element assignment (3.7) has stable names.
 */
materialElements?: Array<string>, anchor3d?: Vec3, 
/**
 * The model's animation clip to play, by name or by index. The keyframe
 * channels that animate this object's own properties are 1.6's; this
 * selects an animation baked into the asset.
 */
clipName?: string, clipIndex?: number, 
/**
 * Playback rate multiplier for the selected clip.
 */
timeScale?: number, 
/**
 * Frames to shift the clip by, relative to the scene timeline.
 */
frameOffset?: number, animationLoop: boolean, id: string, name: string, visible: boolean, locked: boolean, 
/**
 * 0–1.
 */
opacity: number, 
/**
 * Translation in scene coordinates (top-left authoring origin).
 */
x: number, y: number, 
/**
 * Depth along the view axis; composes additively down the hierarchy.
 */
zDepth: number, 
/**
 * Draw order within a layer.
 */
zIndex: number, 
/**
 * The layer this object belongs to (a `Layer` object's id), or empty for
 * the implicit default layer.
 */
layerId: string, 
/**
 * The object's box, in scene units. Every kind has one: a rect and an
 * image fill it, an ellipse is inscribed in it, paragraph text wraps
 * inside it, and a binding can drive it — which is why it is on the base
 * and not repeated per kind.
 */
width: number, height: number, 
/**
 * Rotation in degrees. `rotation` is the Z axis; X and Y are 3D and
 * compose down the hierarchy only on meshes (`resolve_hierarchy`).
 */
rotation: number, rotationX: number, rotationY: number, scaleX: number, scaleY: number, scaleZ: number, 
/**
 * Object-local pivot in scene pixels; renderers apply T(x,y)·R·S·T(-anchor).
 */
anchor?: Vec2, 
/**
 * Primary fill and stroke. Tagged colour values as of 1.4 — a CSS
 * string carried no source space, and B.1 forbids inferring one.
 */
fill?: ColorValue, stroke?: ColorValue, strokeWidth: number, 
/**
 * Bound data paths (object property → data-context path). Opaque here;
 * the binding contract owns the grammar.
 */
bindings?: { [key in string]?: JsonValue }, 
/**
 * Material slot assignments: slot name → the material bound to it
 * (1.3). A `BTreeMap` so the wire order is the slot order and two
 * equal scenes serialise to equal bytes.
 */
materialSlots?: { [key in string]?: MaterialBinding }, };
