// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reply or event. They must never share an id.
 */
export type MessageKind = "Reply" | "Event";
