// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Message identity. Correlates a request with its reply.
 */
export type MessageId = string;
