// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MotionPhases } from "./MotionPhases";
import type { PresetParam } from "./PresetParam";
import type { Stagger } from "./Stagger";

/**
 * A designer-authored motion preset (G.6.4). The model selects and
 * parameterises these; it never authors one (G.6.7).
 */
export type MotionPreset = { id: string, 
/**
 * Object types the preset may be applied to.
 */
appliesTo: Array<string>, phases: MotionPhases, 
/**
 * Adjustable parameters, each with its declared range.
 */
params: Array<PresetParam>, 
/**
 * Required when the preset drives a data-bound repeater (G.6.5).
 */
stagger: Stagger | null, };
