// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MotionKey } from "./MotionKey";

/**
 * One animated property within a phase.
 */
export type MotionChannel = { 
/**
 * The property path, e.g. `position.x`, `opacity`.
 */
property: string, 
/**
 * Keys on the 0–1 normalised timeline (G.6.2).
 */
keys: Array<MotionKey>, };
