// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DurationSpec } from "./DurationSpec";
import type { MotionChannel } from "./MotionChannel";

/**
 * One phase: a duration and the channels it animates.
 */
export type MotionPhase = { 
/**
 * Duration, either a token reference or a literal millisecond count.
 */
duration: DurationSpec, channels: Array<MotionChannel>, };
