// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Named } from "./Named";
import type { NamedEasing } from "./NamedEasing";

/**
 * Motion tokens: the primitives every preset composes from (G.6.1).
 *
 * Durations and staggers are milliseconds. Easings are cubic-bezier control
 * points, or the literal `hold` for a phase that must not interpolate.
 */
export type MotionTokens = { 
/**
 * Named durations in ms, e.g. `snap: 160`, `base: 400`.
 */
duration: Array<Named<number>>, 
/**
 * Named easings.
 */
easing: Array<NamedEasing>, 
/**
 * Named stagger intervals in ms, e.g. `tight: 40`, `base: 70`.
 */
stagger: Array<Named<number>>, };
