// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MotionPhase } from "./MotionPhase";

/**
 * The operator phases a preset participates in (G.6.3).
 *
 * Broadcast motion is not one clip; it maps onto the operator verbs the
 * system already has. A preset must describe each phase it uses, and `in`
 * plus `out` are required.
 */
export type MotionPhases = { 
/**
 * Build on. Triggered by Take. Required.
 */
in: MotionPhase, 
/**
 * Build off. Triggered by Out. Required.
 */
out: MotionPhase, 
/**
 * Idle loop after `in` completes. Must be safely interruptible at any
 * frame.
 */
hold: MotionPhase | null, 
/**
 * Staged builds, triggered by Continue. Zero or more.
 */
continue: Array<MotionPhase>, 
/**
 * How a bound value changes on air without a full re-take.
 */
update: MotionPhase | null, };
