// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A named scalar token value.
 */
export type Named<T> = { name: string, value: T, };
