// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An easing token: a cubic-bezier curve, or `hold`.
 */
export type NamedEasing = { "easing": "bezier", name: string, value: [number, number, number, number], } | { "easing": "hold", name: string, };
