// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorValue } from "./ColorValue";
import type { JsonValue } from "./serde_json/JsonValue";
import type { MaterialBinding } from "./MaterialBinding";
import type { Vec2 } from "./Vec2";

/**
 * Transform, box and appearance state every object carries — the shared core
 * the hierarchy resolver composes and the inspector edits. Ported from 1.x
 * `BaseSceneObject`; what was left behind is listed in the module doc.
 */
export type ObjectBase = { id: string, name: string, visible: boolean, locked: boolean, 
/**
 * 0–1.
 */
opacity: number, 
/**
 * Translation in scene coordinates (top-left authoring origin).
 */
x: number, y: number, 
/**
 * Depth along the view axis; composes additively down the hierarchy.
 */
zDepth: number, 
/**
 * Draw order within a layer.
 */
zIndex: number, 
/**
 * The layer this object belongs to (a `Layer` object's id), or empty for
 * the implicit default layer.
 */
layerId: string, 
/**
 * The object's box, in scene units. Every kind has one: a rect and an
 * image fill it, an ellipse is inscribed in it, paragraph text wraps
 * inside it, and a binding can drive it — which is why it is on the base
 * and not repeated per kind.
 */
width: number, height: number, 
/**
 * Rotation in degrees. `rotation` is the Z axis; X and Y are 3D and
 * compose down the hierarchy only on meshes (`resolve_hierarchy`).
 */
rotation: number, rotationX: number, rotationY: number, scaleX: number, scaleY: number, scaleZ: number, 
/**
 * Object-local pivot in scene pixels; renderers apply T(x,y)·R·S·T(-anchor).
 */
anchor?: Vec2, 
/**
 * Primary fill and stroke. Tagged colour values as of 1.4 — a CSS
 * string carried no source space, and B.1 forbids inferring one.
 */
fill?: ColorValue, stroke?: ColorValue, strokeWidth: number, 
/**
 * Bound data paths (object property → data-context path). Opaque here;
 * the binding contract owns the grammar.
 */
bindings?: { [key in string]?: JsonValue }, 
/**
 * Material slot assignments: slot name → the material bound to it
 * (1.3). A `BTreeMap` so the wire order is the slot order and two
 * equal scenes serialise to equal bytes.
 */
materialSlots?: { [key in string]?: MaterialBinding }, };
