// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output configuration. Live output is gated by ADR-005, evaluated in
 * `crate::capability::live_allowed`.
 */
export type OutputConfig = { 
/**
 * Adapter name. Never used to decide whether the output is live
 * (invariant 20) - it names a device, nothing more.
 */
adapter: string, 
/**
 * Whether this output is intended to reach an audience.
 */
live: boolean, 
/**
 * Set only when an operator has been told the reference is not locked.
 */
acceptFreeRun: boolean, };
