// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The only two transforms an output adapter may apply on the way out.
 */
export type OutputTransform = "srgb" | "rec709";
