// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentHash } from "./ContentHash";

/**
 * One verified payload file in a [`PackageManifest`].
 */
export type PackageFileEntry = { 
/**
 * Archive-relative path, expressed with `/` separators.
 */
path: string, sizeBytes: bigint, sha256: ContentHash, };
