// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageFileEntry } from "./PackageFileEntry";
import type { Revision } from "./Revision";

/**
 * A `.gpxpkg`'s signed-by-content inventory.
 */
export type PackageManifest = { formatVersion: number, 
/**
 * The immutable scene identity this archive contains.
 */
sceneId: string, 
/**
 * The exact scene revision this archive contains.
 */
sceneRevision: Revision, 
/**
 * Every payload member, including [`SCENE_PATH`] but excluding this
 * manifest itself: a manifest cannot hash itself without a circular
 * definition.
 */
files: Array<PackageFileEntry>, };
