// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrushBlendMode } from "./BrushBlendMode";
import type { BrushPoint } from "./BrushPoint";

/**
 * One paint stroke.
 */
export type PaintStroke = { id: string, points: Array<BrushPoint>, size: number, hardness: number, opacity: number, flow: number, spacing: number, smoothing: number, roundness: number, angle: number, color: string, blendMode: BrushBlendMode, };
