// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentHash } from "./ContentHash";

/**
 * Ask the engine what it already holds, so only the difference ships.
 */
export type PreflightRequest = { hashes: Array<ContentHash>, };
