// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentHash } from "./ContentHash";

/**
 * The engine's answer. `missing` is what must be transferred.
 */
export type PreflightResponse = { missing: Array<ContentHash>, };
