// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DurationSpec } from "./DurationSpec";

/**
 * A preset parameter with its declared range (G.6.4).
 */
export type PresetParam = { "type": "enum", name: string, values: Array<string>, default: string, } | { "type": "duration", name: string, min: number, max: number, default: DurationSpec, };
