// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Revision } from "./Revision";
import type { TakeId } from "./TakeId";

/**
 * What is currently on Program, if anything.
 */
export type ProgramState = { takeId: TakeId, revision: Revision, 
/**
 * The frame the engine committed this take to.
 */
committedFrame: bigint, };
