// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A frame rate as an exact rational. Never a float (invariant 12).
 *
 * 29.97 is 30000/1001 and cannot be represented in binary floating point.
 * Accumulating a rounded rate across an 8-hour soak drifts the clock, so this
 * type deliberately offers no `f64` constructor.
 */
export type RationalRate = { num: number, den: number, };
