// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A solid or stroked rectangle.
 */
export type RectObject = { width: number, height: number, fill?: string, id: string, name: string, visible: boolean, 
/**
 * 0–1.
 */
opacity: number, 
/**
 * Translation in scene coordinates.
 */
x: number, y: number, scaleX: number, scaleY: number, 
/**
 * Rotation in degrees.
 */
rotation: number, };
