// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReferenceState } from "./ReferenceState";

/**
 * A reference state change, reported as an event.
 */
export type ReferenceTransition = { from: ReferenceState, to: ReferenceState, 
/**
 * The frame at which the change was observed, in the engine's timebase.
 */
atFrame: bigint, };
