// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * External reference signal state.
 */
export type ReferenceState = "Locked" | "Unlocked" | "NotPresent";
