// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClockSource } from "./ClockSource";
import type { ContentHash } from "./ContentHash";
import type { DeviceTier } from "./DeviceTier";
import type { ReferenceState } from "./ReferenceState";
import type { Revision } from "./Revision";
import type { TakeId } from "./TakeId";

/**
 * First-class, named refusals. No silent substitution (invariant 18).
 *
 * Every variant names the failing condition. A caller that receives one knows
 * what to fix; an agent that receives one learns the contract, which is the
 * whole argument of the automation plan in ADR Part D, M7.
 */
export type Refusal = { "refusal": "revisionMismatch", expected: Revision, actual: Revision, } | { "refusal": "tierTooLow", actual: DeviceTier, } | { "refusal": "referenceUnlocked", state: ReferenceState, } | { "refusal": "unsupportedBlendMode", mode: string, } | { "refusal": "unsupportedFitMode", mode: string, } | { "refusal": "assetMissing", hash: ContentHash, } | { "refusal": "protocolMismatch", expected: number, actual: number, } | { "refusal": "invalidRate", num: number, den: number, } | { "refusal": "platformNotCertified", platform: string, } | { "refusal": "unknownTake", takeId: TakeId, } | { "refusal": "frameNotReachable", requested: bigint, earliest: bigint, } | { "refusal": "multipleClockDomains", existing: ClockSource, requested: ClockSource, } | { "refusal": "unauthenticated" } | { "refusal": "transportFailed", detail: string, } | { "refusal": "notImplemented", what: string, } | { "refusal": "fontMissing", fontId: string, } | { "refusal": "fontUrlNotHttps", url: string, } | { "refusal": "fontUrlHasCredentials", url: string, } | { "refusal": "invalidFontUrl", url: string, } | { "refusal": "fontEmbeddingRefused", fontId: string, } | { "refusal": "invalidFontData", detail: string, };
