// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How urgently a structured refusal must be acted on (0.6). Not everything is
 * a hard rule, so the envelope carries severity alongside the code.
 *
 * Lives in contracts rather than in the validator because the same triage
 * applies to every refusal surface — engine, validator and design system —
 * and three copies would drift (invariant 27).
 *
 * Declared least-urgent first so the derived `Ord` reads as urgency:
 * `Error > Warning > Info`.
 */
export type RefusalSeverity = "info" | "warning" | "error";
