// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Publish revision. Exact-match only: a take against a stale revision is
 * refused, never coerced (invariant 17).
 */
export type Revision = bigint;
