// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceColorSpace } from "./SourceColorSpace";

/**
 * A colour, with the space it was authored in.
 *
 * Components are 0–1 floats rather than 8-bit bytes because the working
 * space is linear and 8 bits of linear has visible banding in the shadows.
 */
export type Rgba = { r: number, g: number, b: number, 
/**
 * Straight (non-premultiplied) alpha.
 */
a: number, space: SourceColorSpace, };
