// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The product identity carried by an authenticated connection.
 */
export type Role = "editor" | "playout" | "engine";
