// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetLibraryItem } from "./AssetLibraryItem";
import type { FontDefinition } from "./FontDefinition";
import type { JsonValue } from "./serde_json/JsonValue";
import type { MaterialDefinition } from "./MaterialDefinition";
import type { Revision } from "./Revision";
import type { SceneCanvas } from "./SceneCanvas";
import type { SceneObject } from "./SceneObject";
import type { SceneTimeline } from "./SceneTimeline";

/**
 * The scene document: the unit the Editor authors, the package carries and
 * the engine prepares. Self-describing — fonts, assets and objects travel
 * together so a published package never depends on outside state.
 */
export type SceneDocument = { id: string, name: string, 
/**
 * Schema version. A reader refuses a version it does not know by name.
 */
version: number, 
/**
 * Monotonic authoring revision; the optimistic-concurrency token (0.8).
 */
revision?: Revision, canvas: SceneCanvas, timeline: SceneTimeline, 
/**
 * Live data the scene's bindings resolve against.
 */
dataContext: { [key in string]?: JsonValue }, 
/**
 * The asset library this scene references.
 */
assets: Array<AssetLibraryItem>, 
/**
 * Fonts available to this scene, resolved package-first.
 */
fonts: Array<FontDefinition>, 
/**
 * The materials this scene's objects bind by id. A scene is
 * self-describing (1.1), so a material slot resolves inside the
 * document or not at all — a library held anywhere else would make a
 * published package depend on outside state.
 */
materials: Array<MaterialDefinition>, 
/**
 * The scene graph, in draw order.
 */
objects: Array<SceneObject>, };
