// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The scene timeline. Minimal for the lean core: duration and markers. The
 * keyframe model lands with the motion consumers that read it.
 */
export type SceneTimeline = { 
/**
 * Total duration in frames at the canvas rate.
 */
durationFrames: bigint, };
