// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RationalRate } from "./RationalRate";

/**
 * The scene's output canvas. Resolution and rate are configuration, never
 * constants (ADR-0002 Part C), and the rate is rational (invariant 12).
 */
export type SceneCanvas = { width: number, height: number, frameRate: RationalRate, };
