// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EllipseObject } from "./EllipseObject";
import type { GroupObject } from "./GroupObject";
import type { ImageObject } from "./ImageObject";
import type { RectObject } from "./RectObject";
import type { TextObject } from "./TextObject";

/**
 * The authorable object kinds. A tagged enum, not an open struct: the set of
 * kinds a scene may contain is a reviewed contract, and the renderer refuses
 * a kind it does not know by name rather than ignoring it (invariant 18).
 */
export type SceneObject = { "type": "text" } & TextObject | { "type": "rect" } & RectObject | { "type": "ellipse" } & EllipseObject | { "type": "image" } & ImageObject | { "type": "group" } & GroupObject;
