// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A closed authority a role may receive in a credential.
 */
export type Scope = "author" | "cue" | "take" | "clear" | "configureOutput" | "report";
