// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Monotonic per-direction message counter. Gaps mean loss, which the control
 * plane does not tolerate.
 */
export type Sequence = bigint;
