// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How urgently the operator must be told. Drives presentation, so that
 * free-run cannot be rendered as quiet grey text (invariant 11).
 */
export type Severity = "Nominal" | "Warning" | "Critical";
