// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One bevel of a slab, measured inward from its outline.
 */
export type SlabBevel = { enabled: boolean, 
/**
 * Width of the bevel, inward from the slab outline, in scene units.
 */
size: number, 
/**
 * Z depth the bevel occupies, in scene units.
 */
depth: number, };
