// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CullMode } from "./CullMode";
import type { SlabBevel } from "./SlabBevel";

/**
 * XPression-style slab controls: a rounded, skewed extrusion with
 * independent front and back bevels. Geometry only — face culling is a
 * material property and arrives with 1.3's material model.
 */
export type SlabProperties = { 
/**
 * Corner radius of the slab outline, in scene units.
 */
cornerRadius: number, 
/**
 * Curved-corner tessellation quality.
 */
cornerSegments: number, 
/**
 * Horizontal displacement between the slab's bottom and top edges.
 */
skew: number, 
/**
 * Whether texture coordinates follow the skewed outline.
 */
skewTexture: boolean, 
/**
 * Object-level face culling, matching XPression's slab control (1.3).
 */
culling: CullMode, frontBevel: SlabBevel, backBevel: SlabBevel, };
