// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a colour or a texture was authored in. There is no `Unknown`: an
 * untagged source is a defect the importer must refuse, not a value a
 * renderer may guess at (B.1, "never infer").
 */
export type SourceColorSpace = "srgb" | "linear" | "display-p3" | "rec709";
