// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a stagger behaves as the item count grows (G.6.5).
 */
export type Stagger = { "mode": "fixed" } | { "mode": "capTotal", max_total: number, } | { "mode": "overlap" };
