// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";
import type { Refusal } from "./Refusal";
import type { RefusalSeverity } from "./RefusalSeverity";

/**
 * The structured refusal envelope (0.6): the shape every refusal surface
 * returns, so a caller — human or agent — can act on it without parsing prose.
 *
 * `Refusal` names *what* was refused; this envelope adds *where*, *what was
 * given*, *what is allowed* and *how urgent it is*. The `allowed` array is
 * what turns a failure into a successful retry: a refusal that names the
 * acceptable values is the difference between an agent that corrects itself
 * and one that guesses again (Part D principle 3, Part G.4).
 *
 * Serialises identically in Rust and TypeScript because it is generated from
 * this one definition (invariant 22); the test below pins the exact JSON.
 */
export type StructuredRefusal = { 
/**
 * The named refusal. The machine-parseable reason.
 */
code: Refusal, 
/**
 * The JSON path to the offending value, e.g. `objects[2].text.size`.
 * Omitted on the wire when the refusal is not about one field.
 *
 * `#[ts(optional)]` keeps the generated TS in step with serde's
 * `skip_serializing_if`: the key is absent, not `null`, so the TS field
 * is `field?: string`, and the two attributes must change together.
 */
field?: string, 
/**
 * The value that was given, as JSON, so the caller can show or log it
 * verbatim. `Null` when there is no single given value.
 */
given: JsonValue, 
/**
 * The values that would have been accepted. Omitted on the wire when
 * there is no enumerable set — the fix is described by the code, not a
 * list.
 */
allowed?: Array<JsonValue>, severity: RefusalSeverity, };
