// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * When a take should happen, expressed as intent.
 *
 * Deliberately has no `Now` variant. Playout does not know what "now" is in
 * the engine's timebase, and on a genlocked output it never will.
 */
export type TakeAt = { "at": "nextOpportunity" } | { "at": "frame", frame: bigint, };
