// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClockSource } from "./ClockSource";
import type { RationalRate } from "./RationalRate";

/**
 * What the engine actually committed to.
 *
 * This is the half of the exchange that makes intent-based control honest:
 * the operator sees a frame number the engine chose, not a request they made.
 */
export type TakeCommitted = { 
/**
 * In the engine's timebase.
 */
frame: bigint, 
/**
 * Rational, never a float (invariant 12).
 */
timebase: RationalRate, clock: ClockSource, };
