// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable identity of a published scene. Survives every republish.
 */
export type TakeId = string;
