// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Revision } from "./Revision";
import type { TakeAt } from "./TakeAt";
import type { TakeId } from "./TakeId";

/**
 * Ask for a take. Revision is exact; a mismatch is refused, not coerced.
 */
export type TakeRequest = { takeId: TakeId, revision: Revision, at: TakeAt, };
