// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Base direction. `Auto` resolves from the first strong character, which is
 * what makes bidi text (3.6) correct without the author declaring it.
 */
export type TextDirection = "auto" | "ltr" | "rtl";
