// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Underline and strikethrough: drawn from the font's metrics rather than
 * shaped, so they are object state and not part of the font definition.
 */
export type TextDecoration = { underline: boolean, strikethrough: boolean, };
