// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Point text grows from its origin; paragraph text wraps inside the base box.
 */
export type TextLayout = "point" | "paragraph";
