// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A text object. The font is referenced by id into the scene's font list —
 * never by a system family name (ADR-0002 A.4's one rule).
 */
export type TextObject = { text: string, 
/**
 * References `FontDefinition::font_id` in the scene's `fonts`.
 */
fontId: string, size: number, color?: string, id: string, name: string, visible: boolean, 
/**
 * 0–1.
 */
opacity: number, 
/**
 * Translation in scene coordinates.
 */
x: number, y: number, scaleX: number, scaleY: number, 
/**
 * Rotation in degrees.
 */
rotation: number, };
