// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Case applied when the text is drawn, not when it is typed: the authored
 * characters stay as they are, so a data binding can replace the text and
 * the case still applies, and switching it off returns the author's own
 * capitalisation.
 */
export type TextCase = "original" | "upper" | "lower" | "title" | "small-caps";
