// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A shared secret presented by a client on connect.
 *
 * Deliberately not `Copy` and deliberately not `Display`: there is no
 * convenient way to print one by accident.
 */
export type Token = string;
