// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A token reference in a preset: `{duration.base}`, `{easing.brand-in}`.
 *
 * A preset that hardcodes a value instead of referencing a token is a bug for
 * the same reason a component hardcoding a hex colour is (G.6.1). Kept as a
 * string with a checked shape rather than a free string, so a malformed
 * reference is caught at parse, not at render.
 */
export type TokenRef = string;
