// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Transfer state for one asset. Restartable by chunk; a partial transfer
 * never becomes a cached asset (invariant 28).
 */
export type TransferState = "Pending" | "InProgress" | "Verified" | "HashMismatch";
