// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A 2D point in scene coordinates.
 */
export type Vec2 = { x: number, y: number, };
