// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A 3D point in scene coordinates.
 */
export type Vec3 = { x: number, y: number, z: number, };
