// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The space every scene is composited in. One variant, deliberately: this
 * type exists so that "render in linear" is a fact of the contract rather
 * than a convention a renderer can quietly break.
 */
export type WorkingColorSpace = "linear-srgb";
