// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * CSS `writing-mode` values, which is what the shaper (3.6) consumes.
 */
export type WritingMode = "horizontal-tb" | "vertical-rl" | "vertical-lr";
