[package]
name = "gx-mock-engine"
edition.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
name = "gx_mock_engine"
path = "src/lib.rs"

[[bin]]
name = "gx-mock-engine"
path = "src/main.rs"

[dependencies]
gx-contracts = { workspace = true }
gx-control-plane = { workspace = true }
gx-control-transport = { workspace = true }
gx-asset-plane = { workspace = true }
serde_json = { workspace = true }
